package:
  name: suds-jurko
  version: !!str 0.6

source:
  fn: suds-jurko-0.6.tar.bz2
  url: https://pypi.python.org/packages/source/s/suds-jurko/suds-jurko-0.6.tar.bz2
  md5: 1309e9bc2454aa3434041f0a24ae4e11
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - suds-jurko = suds-jurko:main
    #
    # Would create an entry point called suds-jurko that calls suds-jurko.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - suds.xsd
    - tests
    - suds.mx
    - suds.transport
    - suds.umx
    - suds.bindings
    - tests.external
    - suds
    - suds.sax

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/jurko/suds
  license: GNU Library or Lesser General Public License (LGPL)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
